name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v2
      - name: "Setup Java"
        uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - name: "Install Flutter"
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.3'
          channel: 'stable'
      - name: "Install dependencies"
        run: flutter pub get
      - name: "Create .env"
        run: touch .env
      - name: "Analyze flutter code"
        run: flutter analyze
      - name: "Build Android app"
        run: flutter build apk --split-per-abi
      
